---
apiVersion: v1
kind: Namespace
metadata:
  name: gymflex

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gymflex-backend
  name: gymflex-backend-deployment
  namespace: gymflex
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gymflex-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gymflex-backend
    spec:
      containers:
        - image: noseyug/be
          imagePullPolicy: Always
          name: gymflex-backend
          ports:
            - containerPort: 3002
              name: tcp
              protocol: TCP

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: gymflex-backend-service
  namespace: gymflex
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: gymflex-backend
  sessionAffinity: None
  type: ClusterIP

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gymflex-frontend
  name: gymflex-frontend-deployment
  namespace: gymflex
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gymflex-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gymflex-frontend
    spec:
      containers:
        - image: noseyug/fe
          imagePullPolicy: Always
          name: gymflex-frontend
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: gymflex-frontend-service
  namespace: gymflex
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gymflex-frontend
  sessionAffinity: None
  type: ClusterIP

---
# Ingress 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gymflex-ingress
  namespace: gymflex
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          # Backend 
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gymflex-backend-service
                port:
                  number: 3002

          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gymflex-frontend-service
                port:
                  number: 80