sonar.projectKey=gym_flex
sonar.projectName=gym_flex

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,frontend/src/pages/**,frontend/src/layouts/**,frontend/src/services/**,frontend/src/data/**,frontend/src/routes/**,frontend/src/styles/**,frontend/src/features/**,frontend/src/components/AllRoute/**,frontend/src/components/CartMenu/**,frontend/src/reportWebVitals.js,frontend/src/index.js,backend/src/server.js,backend/src/cronWebhook.js

sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.css.file.suffixes=.css,.scss,.less

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info