sonar.projectKey=gym_flex
sonar.projectName=gym_flex
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.css.file.suffixes=.css,.scss,.less
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.infosonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info